"""
Script to seed the database with initial iPhone products
Run: python seed_products.py
"""
import asyncio
import os
from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv
from pathlib import Path
import uuid
from datetime import datetime, timezone

ROOT_DIR = Path(__file__).parent
load_dotenv(ROOT_DIR / '.env')

# MongoDB connection
mongo_url = os.environ['MONGO_URL']
client = AsyncIOMotorClient(mongo_url)
db = client[os.environ['DB_NAME']]


# Sample products data
PRODUCTS = [
    # iPhone 17 Series
    {
        "id": str(uuid.uuid4()),
        "name": "iPhone 17 Pro Max",
        "model": "17",
        "type": "pro-max",
        "storage": "256GB",
        "color": "Negro Titanio",
        "condition": "sealed",
        "battery_health": 100,
        "price_ars": 1850000,
        "price_usd": 1850,
        "screen_size": "6.7\" Super Retina XDR",
        "chip": "A19 Pro",
        "camera": "48MP Principal + 12MP Ultra Gran Angular",
        "features": ["5G", "ProMotion 120Hz", "Dynamic Island", "Action Button"],
        "available": True,
        "warranty_months": 12,
        "description": "El iPhone más avanzado hasta ahora. Diseño en titanio con el chip A19 Pro de última generación.",
        "image_url": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-17-pro-max-finish-select-202409-6-7inch-naturaltitanium?wid=5120&hei=2880",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": str(uuid.uuid4()),
        "name": "iPhone 17 Pro",
        "model": "17",
        "type": "pro",
        "storage": "128GB",
        "color": "Azul Titanio",
        "condition": "sealed",
        "battery_health": 100,
        "price_ars": 1650000,
        "price_usd": 1650,
        "screen_size": "6.3\" Super Retina XDR",
        "chip": "A19 Pro",
        "camera": "48MP Principal + 12MP Ultra Gran Angular",
        "features": ["5G", "ProMotion 120Hz", "Dynamic Island", "Action Button"],
        "available": True,
        "warranty_months": 12,
        "description": "Potencia Pro en un formato más compacto. Titanio premium y rendimiento sin compromisos.",
        "image_url": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-17-pro-finish-select-202409-6-3inch-bluetitanium?wid=5120&hei=2880",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat()
    },
    # iPhone 16 Series
    {
        "id": str(uuid.uuid4()),
        "name": "iPhone 16 Pro Max",
        "model": "16",
        "type": "pro-max",
        "storage": "512GB",
        "color": "Natural Titanio",
        "condition": "like-new",
        "battery_health": 98,
        "price_ars": 1550000,
        "price_usd": 1550,
        "screen_size": "6.9\" Super Retina XDR",
        "chip": "A18 Pro",
        "camera": "48MP Principal",
        "features": ["5G", "ProMotion 120Hz", "Dynamic Island", "USB-C"],
        "available": True,
        "warranty_months": 6,
        "description": "Como nuevo. La pantalla más grande de iPhone con rendimiento profesional.",
        "image_url": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-16-pro-max-finish-select-202409-6-9inch-naturaltitanium?wid=5120&hei=2880",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": str(uuid.uuid4()),
        "name": "iPhone 16 Pro",
        "model": "16",
        "type": "pro",
        "storage": "256GB",
        "color": "Desert Titanio",
        "condition": "excellent",
        "battery_health": 95,
        "price_ars": 1350000,
        "price_usd": 1350,
        "screen_size": "6.3\" Super Retina XDR",
        "chip": "A18 Pro",
        "camera": "48MP Principal",
        "features": ["5G", "ProMotion 120Hz", "Dynamic Island", "USB-C"],
        "available": True,
        "warranty_months": 6,
        "description": "Estado excelente. Potencia profesional en formato compacto.",
        "image_url": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-16-pro-finish-select-202409-6-3inch-deserttitanium?wid=5120&hei=2880",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": str(uuid.uuid4()),
        "name": "iPhone 16 Plus",
        "model": "16",
        "type": "plus",
        "storage": "256GB",
        "color": "Rosa",
        "condition": "like-new",
        "battery_health": 97,
        "price_ars": 1200000,
        "price_usd": 1200,
        "screen_size": "6.7\" Super Retina XDR",
        "chip": "A18",
        "camera": "48MP Principal",
        "features": ["5G", "Dynamic Island", "USB-C", "Ceramic Shield"],
        "available": True,
        "warranty_months": 6,
        "description": "Pantalla grande con batería de larga duración. Como nuevo.",
        "image_url": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-16-plus-finish-select-202409-6-7inch-pink?wid=5120&hei=2880",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": str(uuid.uuid4()),
        "name": "iPhone 16",
        "model": "16",
        "type": "normal",
        "storage": "128GB",
        "color": "Ultramarine",
        "condition": "excellent",
        "battery_health": 94,
        "price_ars": 1050000,
        "price_usd": 1050,
        "screen_size": "6.1\" Super Retina XDR",
        "chip": "A18",
        "camera": "48MP Principal",
        "features": ["5G", "Dynamic Island", "USB-C", "Ceramic Shield"],
        "available": True,
        "warranty_months": 3,
        "description": "El equilibrio perfecto entre tamaño y rendimiento.",
        "image_url": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-16-finish-select-202409-6-1inch-ultramarine?wid=5120&hei=2880",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat()
    },
    # iPhone 15 Series
    {
        "id": str(uuid.uuid4()),
        "name": "iPhone 15 Pro Max",
        "model": "15",
        "type": "pro-max",
        "storage": "256GB",
        "color": "Natural Titanio",
        "condition": "excellent",
        "battery_health": 88,
        "price_ars": 1250000,
        "price_usd": 1250,
        "screen_size": "6.7\" Super Retina XDR",
        "chip": "A17 Pro",
        "camera": "48MP Principal",
        "features": ["5G", "ProMotion 120Hz", "USB-C", "Titanio"],
        "available": True,
        "warranty_months": 3,
        "description": "El primer iPhone con titanio. Potencia y elegancia.",
        "image_url": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-15-pro-max-finish-select-202309-6-7inch-naturaltitanium?wid=5120&hei=2880",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": str(uuid.uuid4()),
        "name": "iPhone 15 Pro",
        "model": "15",
        "type": "pro",
        "storage": "128GB",
        "color": "Azul Titanio",
        "condition": "excellent",
        "battery_health": 86,
        "price_ars": 1050000,
        "price_usd": 1050,
        "screen_size": "6.1\" Super Retina XDR",
        "chip": "A17 Pro",
        "camera": "48MP Principal",
        "features": ["5G", "ProMotion 120Hz", "USB-C", "Titanio"],
        "available": True,
        "warranty_months": 3,
        "description": "Rendimiento profesional en un diseño compacto de titanio.",
        "image_url": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-15-pro-finish-select-202309-6-1inch-bluetitanium?wid=5120&hei=2880",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": str(uuid.uuid4()),
        "name": "iPhone 15 Plus",
        "model": "15",
        "type": "plus",
        "storage": "128GB",
        "color": "Negro",
        "condition": "good",
        "battery_health": 85,
        "price_ars": 950000,
        "price_usd": 950,
        "screen_size": "6.7\" Super Retina XDR",
        "chip": "A16 Bionic",
        "camera": "48MP Principal",
        "features": ["5G", "Dynamic Island", "USB-C", "Ceramic Shield"],
        "available": True,
        "warranty_months": 0,
        "description": "Pantalla grande con excelente autonomía. Buen estado.",
        "image_url": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-15-plus-finish-select-202309-6-7inch-black?wid=5120&hei=2880",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": str(uuid.uuid4()),
        "name": "iPhone 15",
        "model": "15",
        "type": "normal",
        "storage": "128GB",
        "color": "Rosa",
        "condition": "excellent",
        "battery_health": 89,
        "price_ars": 850000,
        "price_usd": 850,
        "screen_size": "6.1\" Super Retina XDR",
        "chip": "A16 Bionic",
        "camera": "48MP Principal",
        "features": ["5G", "Dynamic Island", "USB-C", "Ceramic Shield"],
        "available": True,
        "warranty_months": 3,
        "description": "El iPhone esencial con Dynamic Island y USB-C.",
        "image_url": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-15-finish-select-202309-6-1inch-pink?wid=5120&hei=2880",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat()
    },
    # iPhone 14 Series
    {
        "id": str(uuid.uuid4()),
        "name": "iPhone 14 Pro Max",
        "model": "14",
        "type": "pro-max",
        "storage": "256GB",
        "color": "Púrpura Profundo",
        "condition": "excellent",
        "battery_health": 84,
        "price_ars": 1000000,
        "price_usd": 1000,
        "screen_size": "6.7\" Super Retina XDR",
        "chip": "A16 Bionic",
        "camera": "48MP Principal",
        "features": ["5G", "ProMotion 120Hz", "Dynamic Island", "Always-On"],
        "available": True,
        "warranty_months": 0,
        "description": "El primer iPhone con Dynamic Island y Always-On Display.",
        "image_url": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-14-pro-max-finish-select-202209-6-7inch-deeppurple?wid=5120&hei=2880",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": str(uuid.uuid4()),
        "name": "iPhone 14 Pro",
        "model": "14",
        "type": "pro",
        "storage": "128GB",
        "color": "Plata",
        "condition": "excellent",
        "battery_health": 82,
        "price_ars": 850000,
        "price_usd": 850,
        "screen_size": "6.1\" Super Retina XDR",
        "chip": "A16 Bionic",
        "camera": "48MP Principal",
        "features": ["5G", "ProMotion 120Hz", "Dynamic Island", "Always-On"],
        "available": True,
        "warranty_months": 0,
        "description": "Rendimiento Pro con Dynamic Island en un tamaño perfecto.",
        "image_url": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-14-pro-finish-select-202209-6-1inch-silver?wid=5120&hei=2880",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": str(uuid.uuid4()),
        "name": "iPhone 14 Plus",
        "model": "14",
        "type": "plus",
        "storage": "128GB",
        "color": "Azul",
        "condition": "good",
        "battery_health": 79,
        "price_ars": 750000,
        "price_usd": 750,
        "screen_size": "6.7\" Super Retina XDR",
        "chip": "A15 Bionic",
        "camera": "12MP Dual",
        "features": ["5G", "Ceramic Shield", "Night Mode", "Cinematic Mode"],
        "available": True,
        "warranty_months": 0,
        "description": "Pantalla grande y batería excepcional. Buen estado.",
        "image_url": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-14-plus-finish-select-202209-6-7inch-blue?wid=5120&hei=2880",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": str(uuid.uuid4()),
        "name": "iPhone 14",
        "model": "14",
        "type": "normal",
        "storage": "128GB",
        "color": "Medianoche",
        "condition": "good",
        "battery_health": 77,
        "price_ars": 650000,
        "price_usd": 650,
        "screen_size": "6.1\" Super Retina XDR",
        "chip": "A15 Bionic",
        "camera": "12MP Dual",
        "features": ["5G", "Ceramic Shield", "Night Mode", "Cinematic Mode"],
        "available": True,
        "warranty_months": 0,
        "description": "iPhone confiable y potente para el día a día.",
        "image_url": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-14-finish-select-202209-6-1inch-midnight?wid=5120&hei=2880",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat()
    },
    # iPhone 13 Series
    {
        "id": str(uuid.uuid4()),
        "name": "iPhone 13 Pro Max",
        "model": "13",
        "type": "pro-max",
        "storage": "256GB",
        "color": "Grafito",
        "condition": "good",
        "battery_health": 78,
        "price_ars": 800000,
        "price_usd": 800,
        "screen_size": "6.7\" Super Retina XDR",
        "chip": "A15 Bionic",
        "camera": "12MP Triple",
        "features": ["5G", "ProMotion 120Hz", "Ceramic Shield", "Night Mode"],
        "available": True,
        "warranty_months": 0,
        "description": "Pro Max con ProMotion. Excelente relación calidad-precio.",
        "image_url": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-13-pro-max-graphite-select?wid=5120&hei=2880",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": str(uuid.uuid4()),
        "name": "iPhone 13 Pro",
        "model": "13",
        "type": "pro",
        "storage": "128GB",
        "color": "Azul Sierra",
        "condition": "good",
        "battery_health": 76,
        "price_ars": 700000,
        "price_usd": 700,
        "screen_size": "6.1\" Super Retina XDR",
        "chip": "A15 Bionic",
        "camera": "12MP Triple",
        "features": ["5G", "ProMotion 120Hz", "Ceramic Shield", "Night Mode"],
        "available": True,
        "warranty_months": 0,
        "description": "iPhone Pro con pantalla de 120Hz. Gran rendimiento.",
        "image_url": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-13-pro-sierra-blue-select?wid=5120&hei=2880",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": str(uuid.uuid4()),
        "name": "iPhone 13",
        "model": "13",
        "type": "normal",
        "storage": "128GB",
        "color": "Rosa",
        "condition": "good",
        "battery_health": 73,
        "price_ars": 550000,
        "price_usd": 550,
        "screen_size": "6.1\" Super Retina XDR",
        "chip": "A15 Bionic",
        "camera": "12MP Dual",
        "features": ["5G", "Ceramic Shield", "Night Mode", "Cinematic Mode"],
        "available": True,
        "warranty_months": 0,
        "description": "iPhone confiable con excelente rendimiento y 5G.",
        "image_url": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-13-pink-select-2021?wid=5120&hei=2880",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": str(uuid.uuid4()),
        "name": "iPhone 13 mini",
        "model": "13",
        "type": "mini",
        "storage": "128GB",
        "color": "Azul",
        "condition": "good",
        "battery_health": 74,
        "price_ars": 500000,
        "price_usd": 500,
        "screen_size": "5.4\" Super Retina XDR",
        "chip": "A15 Bionic",
        "camera": "12MP Dual",
        "features": ["5G", "Ceramic Shield", "Night Mode", "Compacto"],
        "available": True,
        "warranty_months": 0,
        "description": "Potencia completa en formato mini. Perfecto para una mano.",
        "image_url": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-13-mini-blue-select-2021?wid=5120&hei=2880",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat()
    },
    # iPhone 12 Series
    {
        "id": str(uuid.uuid4()),
        "name": "iPhone 12 Pro Max",
        "model": "12",
        "type": "pro-max",
        "storage": "128GB",
        "color": "Oro",
        "condition": "good",
        "battery_health": 72,
        "price_ars": 650000,
        "price_usd": 650,
        "screen_size": "6.7\" Super Retina XDR",
        "chip": "A14 Bionic",
        "camera": "12MP Triple",
        "features": ["5G", "Ceramic Shield", "LiDAR", "Night Mode"],
        "available": True,
        "warranty_months": 0,
        "description": "El primer Pro Max con 5G. Pantalla grande y potente.",
        "image_url": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-12-pro-max-gold-select?wid=5120&hei=2880",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": str(uuid.uuid4()),
        "name": "iPhone 12 Pro",
        "model": "12",
        "type": "pro",
        "storage": "128GB",
        "color": "Pacífico Azul",
        "condition": "good",
        "battery_health": 70,
        "price_ars": 550000,
        "price_usd": 550,
        "screen_size": "6.1\" Super Retina XDR",
        "chip": "A14 Bionic",
        "camera": "12MP Triple",
        "features": ["5G", "Ceramic Shield", "LiDAR", "Night Mode"],
        "available": True,
        "warranty_months": 0,
        "description": "iPhone Pro con diseño plano icónico y LiDAR.",
        "image_url": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-12-pro-blue-select?wid=5120&hei=2880",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": str(uuid.uuid4()),
        "name": "iPhone 12",
        "model": "12",
        "type": "normal",
        "storage": "64GB",
        "color": "Azul",
        "condition": "good",
        "battery_health": 68,
        "price_ars": 450000,
        "price_usd": 450,
        "screen_size": "6.1\" Super Retina XDR",
        "chip": "A14 Bionic",
        "camera": "12MP Dual",
        "features": ["5G", "Ceramic Shield", "Night Mode", "MagSafe"],
        "available": True,
        "warranty_months": 0,
        "description": "El primer iPhone con 5G. Diseño plano moderno.",
        "image_url": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-12-blue-select-2020?wid=5120&hei=2880",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": str(uuid.uuid4()),
        "name": "iPhone 12 mini",
        "model": "12",
        "type": "mini",
        "storage": "64GB",
        "color": "Verde",
        "condition": "good",
        "battery_health": 69,
        "price_ars": 400000,
        "price_usd": 400,
        "screen_size": "5.4\" Super Retina XDR",
        "chip": "A14 Bionic",
        "camera": "12MP Dual",
        "features": ["5G", "Ceramic Shield", "Night Mode", "Compacto"],
        "available": True,
        "warranty_months": 0,
        "description": "5G en el formato más compacto. Ideal para una mano.",
        "image_url": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-12-mini-green-select-2020?wid=5120&hei=2880",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat()
    },
    # iPhone 11 Series
    {
        "id": str(uuid.uuid4()),
        "name": "iPhone 11 Pro Max",
        "model": "11",
        "type": "pro-max",
        "storage": "256GB",
        "color": "Verde Noche",
        "condition": "good",
        "battery_health": 67,
        "price_ars": 500000,
        "price_usd": 500,
        "screen_size": "6.5\" Super Retina XDR",
        "chip": "A13 Bionic",
        "camera": "12MP Triple",
        "features": ["4G", "Night Mode", "Deep Fusion", "Ultra Wide"],
        "available": True,
        "warranty_months": 0,
        "description": "Triple cámara profesional con increíble autonomía.",
        "image_url": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-11-pro-max-midnight-green-select-2019?wid=5120&hei=2880",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": str(uuid.uuid4()),
        "name": "iPhone 11 Pro",
        "model": "11",
        "type": "pro",
        "storage": "64GB",
        "color": "Gris Espacial",
        "condition": "good",
        "battery_health": 65,
        "price_ars": 420000,
        "price_usd": 420,
        "screen_size": "5.8\" Super Retina XDR",
        "chip": "A13 Bionic",
        "camera": "12MP Triple",
        "features": ["4G", "Night Mode", "Deep Fusion", "Ultra Wide"],
        "available": True,
        "warranty_months": 0,
        "description": "iPhone Pro compacto con sistema de triple cámara.",
        "image_url": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-11-pro-space-gray-select-2019?wid=5120&hei=2880",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": str(uuid.uuid4()),
        "name": "iPhone 11",
        "model": "11",
        "type": "normal",
        "storage": "128GB",
        "color": "Negro",
        "condition": "good",
        "battery_health": 64,
        "price_ars": 350000,
        "price_usd": 350,
        "screen_size": "6.1\" Liquid Retina HD",
        "chip": "A13 Bionic",
        "camera": "12MP Dual",
        "features": ["4G", "Night Mode", "Ultra Wide", "Liquid Retina"],
        "available": True,
        "warranty_months": 0,
        "description": "iPhone con gran batería y cámara dual. Excelente valor.",
        "image_url": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-11-black-select-2019?wid=5120&hei=2880",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat()
    },
    # iPhone SE
    {
        "id": str(uuid.uuid4()),
        "name": "iPhone SE (3ra Gen)",
        "model": "se",
        "type": "se",
        "storage": "128GB",
        "color": "Medianoche",
        "condition": "sealed",
        "battery_health": 100,
        "price_ars": 520000,
        "price_usd": 520,
        "screen_size": "4.7\" Retina HD",
        "chip": "A15 Bionic",
        "camera": "12MP",
        "features": ["5G", "Touch ID", "Compacto", "A15 Bionic"],
        "available": True,
        "warranty_months": 12,
        "description": "El iPhone más accesible con chip A15 y Touch ID. Sellado de fábrica.",
        "image_url": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-se-midnight-select?wid=5120&hei=2880",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": str(uuid.uuid4()),
        "name": "iPhone SE (3ra Gen)",
        "model": "se",
        "type": "se",
        "storage": "64GB",
        "color": "Blanco Estrella",
        "condition": "like-new",
        "battery_health": 98,
        "price_ars": 450000,
        "price_usd": 450,
        "screen_size": "4.7\" Retina HD",
        "chip": "A15 Bionic",
        "camera": "12MP",
        "features": ["5G", "Touch ID", "Compacto", "A15 Bionic"],
        "available": True,
        "warranty_months": 6,
        "description": "Potencia de iPhone 15 en formato clásico. Como nuevo.",
        "image_url": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-se-starlight-select?wid=5120&hei=2880",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat()
    }
]


async def seed_database():
    """Seed the database with initial products"""
    try:
        # Clear existing products
        await db.products.delete_many({})
        print("Cleared existing products...")
        
        # Insert new products
        result = await db.products.insert_many(PRODUCTS)
        print(f"✅ Successfully inserted {len(result.inserted_ids)} products!")
        
        # Display summary
        total = await db.products.count_documents({})
        print(f"\n📊 Database Summary:")
        print(f"   Total Products: {total}")
        
        # Count by model
        models = ["17", "16", "15", "14", "13", "12", "11", "se"]
        for model in models:
            count = await db.products.count_documents({"model": model})
            if count > 0:
                print(f"   iPhone {model}: {count}")
        
    except Exception as e:
        print(f"❌ Error seeding database: {e}")
    finally:
        client.close()


if __name__ == "__main__":
    print("🌱 Seeding database with Mathi Phone products...")
    asyncio.run(seed_database())
